name: Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings .
